spring.application.name=AICampusBot

server.port=8080

openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.key=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